## You have been provided with a dataset named students_performance.csv, which contains various features related to students' performance in exams. The dataset includes features such as gender, race/ethnicity, parental level of education, lunch, test preparation course, and scores in math, reading, and writing. Your task is to perform classification to predict whether a student will pass or fail based on these features.Steps to complete:
- 1.Load the Dataset:oLoad the dataset students_performance.csv into a pandas DataFrame.
oDisplay the first few rows to understand the structure of the dataset and check the sta s cs.
- 2.Preprocessing:
 oConvert the scores in math, reading, and wri ng to a binary pass/fail label. Consider a score of 50 or above as pass(1) and 
below 50 as fail(0).
 oDrop the scores in math, reading, and wri ng.
 oCreate a new Column named ‘Overall_Pass’ and create a binary label: pass(1) if Student passes all heads (math, reading, and 
writing) and fail(0) if student has failed in even one head.
 oEncode categorical variables (gender, race/ethnicity, parental level of educa on, lunch, test prepara on course) using one
hot encoding.
 oHandle any missing values if present.
 oSplit the dataset into features (x) and target (y) where the target is the pass/fail label for the math pass.
 oSplit the data into training (80%) sets using random state 10.

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix
import matplotlib.pyplot as plt

In [15]:
df=pd.read_csv('https://raw.githubusercontent.com/patelmanishv/Sem4Data/refs/heads/main/Datasets/StudentsPerformance.csv')
df

     gender race/ethnicity parental level of education  ... math score reading score  writing score
0    female        group B           bachelor's degree  ...         72            72             74
1    female        group C                some college  ...         69            90             88
2    female        group B             master's degree  ...         90            95             93
3      male        group A          associate's degree  ...         47            57             44
4      male        group C                some college  ...         76            78             75
..      ...            ...                         ...  ...        ...           ...            ...
995  female        group E             master's degree  ...         88            99             95
996    male        group C                 high school  ...         62            55             55
997  female        group C                 high school  ...         59            71             65
998  female        group D                some college  ...         68            78             77
999  female        group D                some college  ...         77            86             86

[1000 rows x 8 columns]

In [6]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [17]:
df['math_pass']=np.where(df['math score']>=50,1,0)
df['writing_pass']=np.where(df['writing score']>=50,1,0)
df['reading_pass']=np.where(df['reading score']>=50,1,0)
df['overall_pass']=np.where(
    (df['math score'] ==1)&
    (df['writing score'] ==1)&
    (df['reading score']==1),1,0
    
)

In [18]:
df

     gender race/ethnicity parental level of education  ... writing_pass reading_pass  overall_pass
0    female        group B           bachelor's degree  ...            1            1             0
1    female        group C                some college  ...            1            1             0
2    female        group B             master's degree  ...            1            1             0
3      male        group A          associate's degree  ...            0            1             0
4      male        group C                some college  ...            1            1             0
..      ...            ...                         ...  ...          ...          ...           ...
995  female        group E             master's degree  ...            1            1             0
996    male        group C                 high school  ...            1            1             0
997  female        group C                 high school  ...            1            1             0
998  female        group D                some college  ...            1            1             0
999  female        group D                some college  ...            1            1             0

[1000 rows x 12 columns]

In [9]:
df.drop(['math score','reading score','writing score'],axis=1,inplace=True)

In [10]:
df

     gender race/ethnicity parental level of education         lunch test preparation course  overall_pass
0    female        group B           bachelor's degree      standard                    none             1
1    female        group C                some college      standard               completed             1
2    female        group B             master's degree      standard                    none             1
3      male        group A          associate's degree  free/reduced                    none             0
4      male        group C                some college      standard                    none             1
..      ...            ...                         ...           ...                     ...           ...
995  female        group E             master's degree      standard               completed             1
996    male        group C                 high school  free/reduced                    none             1
997  female        group C                 high school  free/reduced               completed             1
998  female        group D                some college      standard               completed             1
999  female        group D                some college  free/reduced                    none             1

[1000 rows x 6 columns]

In [19]:
## one hot encoding
df.info()
categorical=['gender','race/ethnicity','parental level of education','lunch','test preparation course']
df_encoded=pd.get_dummies(df.drop(columns=['math_pass']),columns=categorical,drop_first=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
 8   math_pass                    1000 non-null   int64
 9   writing_pass                 1000 non-null   int64
 10  reading_pass                 1000 non-null   int64
 11  overall_pass                 1000 non-null   int64
dtypes: int64(7), object(5)
memory usage: 93.9+ KB

In [20]:
df_encoded.isna().sum()

math score                                       0
reading score                                    0
writing score                                    0
writing_pass                                     0
reading_pass                                     0
overall_pass                                     0
gender_male                                      0
race/ethnicity_group B                           0
race/ethnicity_group C                           0
race/ethnicity_group D                           0
race/ethnicity_group E                           0
parental level of education_bachelor's degree    0
parental level of education_high school          0
parental level of education_master's degree      0
parental level of education_some college         0
parental level of education_some high school     0
lunch_standard                                   0
test preparation course_none                     0
dtype: int64

In [21]:
x=df_encoded
y=df['math_pass']
print(x.shape)
print(y.shape)

(1000, 18)
(1000,)

In [25]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10)

In [28]:
best_k=1
best_accuracy=0
for k in range(1,21):
    knn=KNeighborsClassifier(n_neighbors=k)
    knn.fit(x_train,y_train)
    pred=knn.predict(x_test)
    acc=accuracy_score(y_test,pred)
    if acc>best_accuracy:
        best_k=k
        best_accuracy=acc

In [29]:
print(best_k)
print(best_accuracya)

1
0.98

In [30]:
knn1=KNeighborsClassifier(n_neighbors=best_k)
knn1.fit(x_train,y_train)
pred1=knn.predict(x_test)
cm_knn=confusion_matrix(y_test,pred1)
tn,fp,fn,tp=cm_knn.ravel()
acc1=accuracy_score(y_test,pred1)